- name: Install Docker Compose
  hosts: webservers
  become: yes
  tasks:
    - name: Get the latest stable Docker Compose version
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_release

    - name: Set Docker Compose version fact
      ansible.builtin.set_fact:
        compose_version: "{{ compose_release.json.tag_name }}"

    - name: Download Docker Compose binary
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        force: yes

    - name: Create symbolic link for docker-compose command
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes
